-- INSERT BASE CATEGORIES
INSERT INTO CATEGORIES (libelle) VALUES ('Informatique');
INSERT INTO CATEGORIES (libelle) VALUES ('Ameublement');
INSERT INTO CATEGORIES (libelle) VALUES ('Vetement');
INSERT INTO CATEGORIES (libelle) VALUES ('Sport&Loisir');
